yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:pk>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/users/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path
from . import views

app_name = 'users'


urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста')
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='posts'
    )
    group = models.ForeignKey(
        Group, blank=True,
        null=True, on_delete=models.SET_NULL,
        verbose_name='Группа',
        related_name='posts',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self):
        return self.text[:15]

    class Meta:
        ordering = ['-pub_date']

yatube/posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {'text': 'Текст поста', 'group': 'Выберите группу'}
        help_texts = {'text': 'Текст поста', 'group': 'Выберите группу'}

    def clean_text(self):
        data = self.cleaned_data['text']
        if data == '':
            raise forms.ValidationError('Заполните поле')
        return data

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/core/views.py
from django.shortcuts import render


def page_not_found(request, exception):
    return render(request, 'core/404.html', {'path': request.path}, status=404)


def csrf_failure(request, reason=''):
    return render(request, 'core/403csrf.html')

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .forms import PostForm
from .models import Post, Group, User
from .utils import get_paginator_obj

TITLE_COUNT_SYMBOL: int = 30


def index(request):
    post_list = Post.objects.select_related('author', 'group')
    page_obj = get_paginator_obj(post_list, request)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.select_related('group', 'author')
    page_obj = get_paginator_obj(post_list, request)
    context = {
        'group': group,
        'page_obj': page_obj,
        'title': f'Записи сообщестава: {group}',
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    user_posts = author.posts.select_related(
        'author',
        'group'
    )
    posts_count = Post.objects.filter(author=author).count()
    page_obj = get_paginator_obj(user_posts, request)
    context = {
        'page_obj': page_obj,
        'posts_count': posts_count,
        'author': author,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    author_post = Post.objects.select_related('author')
    post_count = author_post.count()
    title = post.text[:TITLE_COUNT_SYMBOL]
    context = {
        'title': title,
        'post': post,
        'post_count': post_count,
        'author_post': author_post,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    user = get_object_or_404(User, id=request.user.pk)
    form = PostForm(request.POST or None)

    if form.is_valid():
        new_post = form.save(commit=False)
        new_post.author = request.user
        new_post.save()
        return redirect(reverse('posts:profile', args=[user]))
    return render(
        request,
        'posts/create_post.html', {'form': form})


def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user != post.author:
        return redirect(reverse('posts:post_detail', args=[post_id]))
    is_edit = True
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post)
    if form.is_valid():
        form.save()
        return redirect(reverse('posts:post_detail', args=[post_id]))
    context = {
        'is_edit': is_edit,
        'post': post,
        'form': form
    }
    return render(request, 'posts/create_post.html', context)

yatube/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<h1>Привет, я Фарид</h1>
<p>
    Это мой певый сайт. Тут я размещю разную чепуху, что захочу.<br>
    Пришел в программирование не гадано, не жданно. Долго думал, что да как.<br>
    Потом еще долго думал, а правльно ли все решил. А сейчас, думаю, что приходит какое-то осознание, что это то, чем нужно заниматся.

</p>
{% endblock %}

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
<div class="row">
  <h1>Вот что я умею</h1>
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Пока только учусь писать код на Python. Мне начинает все больше нравится это занятие.
        Конечно бывает трудно иногда, при решениее сложных и непонятных задач. Но с каждым разом это становится интересно.

      </li>
      <li class="list-group-item">
        Django это хороший framework в котором есть все необходимые инстументы для создания web-страниц. 
        Конечно я пока только учусь, а на меня навалилось столько информации о Django, что это все трудно усвоить с первого раза. 
        Но думаю это стоит того. 
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    <p>Текст страницы "Технологии"</p>
    О компьютерных технологиях можно говорить долго. Скажу только, что это "взрыв мозга".
  </article>
</div>
{% endblock %}

yatube/templates/base.html
{% load static %}
<!DOCTYPE html> 
<html lang="ru">          
  <head> 
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="/img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="/img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
    <title>
      {% block title %} {% endblock %}
    </title>
  </head>
  <body>       
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
    {% block content %}
    {% endblock %}
    </main>
    <footer>
      {% include 'includes/footer.html' %} 
    </footer>
  </body>
</html>

yatube/templates/core/403csrf.html
{% extends "base.html" %}
{% block content %}
  <h1>Custom CSRF check error. 403</h1>
{% endblock %}

yatube/templates/includes/article.html
<article>
<ul>{% if main_cite %}
    <li>
        Автор: {{ post.author.get_full_name }}
        <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
    </li>
    {% endif %}
    <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
</ul>
<p>{{ post.text }}</p> 
<a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
<br>{% if not group_list %}
    {% if post.group %}
    <a href=" {% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
    {% endif %}
</article>

yatube/templates/includes/errors_authenticat.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}            
            <div class="alert alert-danger">
                {{ error|escape }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ error|escape }}
        </div>
    {% endfor %}
{% endif %}

yatube/templates/includes/footer.html
<div class="border-top text-center py-3">
    <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>    
</div>

yatube/templates/includes/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}            
            <div class="alert alert-danger">
                {{ error|escape }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ error|escape }}
        </div>
    {% endfor %}
{% endif %}

yatube/templates/includes/form_template.html
{% load user_filters %}
<div class="form-group row my-3 p-3"
    {% if field.field.required %} 
    aria-required="true"
    {% else %}
    aria-required="false"
    {% endif %}>
    <label for="{{ field.id_for_label }}">
        {{ field.label }}
    {% if field.field.required %}
        <span class="required text-danger">*</span>
    {% endif %}
    </label>
        {{ field|addclass:'form-control' }}
    {% if field.help_text %}
        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
        {{ field.help_text|safe }}
        </small>
    {% endif %}
</div>

yatube/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      {% with request.resolver_match.view_name as view_name %}
      <ul class="nav nav-pills">
        <li class="nav-item"> 
          <a class="nav-link 
          {% if view_name  == 'about:author' %}
          active
        {% endif %}" href="{% url 'about:author' %}">Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link
          {% if view_name  == 'about:tech' %}
          active
        {% endif %}" href="{% url 'about:tech' %} ">Технологии</a>
        </li>
         {% if request.user.is_authenticated %}
        <li class="nav-item"> 
          <a class="nav-link
          {% if view_name  == 'posts:post_create' %}
          active
        {% endif %}" href="{% url 'posts:post_create' %}">Новая запись</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light
          {% if view_name  == 'about:author' %}
          active
        {% endif %}" href="<!--  -->">Изменить пароль</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light" href="{% url 'users:logout' %} ">Выйти</a>
        </li>
        <li>
          Пользователь: {{ user.username }}
        </li>
        {% else %}
        <li class="nav-item"> 
          <a class="nav-link link-light
          {% if view_name  == 'users:login' %}
          active
        {% endif %}" href="{% url 'users:login' %} ">Войти</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light
          {% if view_name  == 'users:signup' %}
          active
        {% endif %}" href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        {% endif %}
      </ul>
      {% endwith %}
    </div>
  </nav>      
</header>    

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
{% if is_edit %}
  Редактировать запись
{% else %}
  Новый пост
{% endif %} {% endblock %}
  {% include 'includes/header.html' %}
{% block content %}
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                {% if is_edit %}
                  Редактировать запись
                {% else %}
                  Новый пост
                {% endif %}                           
              </div>
              <div class="card-body">        
                <form method="post" enctype="multipart/form-data" action="{% if is_edit %}
                    {% url 'posts:post_edit' post.id %}
                    {% else %}{% url 'posts:post_create' %}
                    {% endif %}">
                  {% csrf_token %}
                {% for field in form %}
                  {% include 'includes/form_template.html' %}
                {% endfor %}
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %} 
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  {{ title }}
{% endblock %}
{% block content %}
  <div class="container py-5">
  <h1> {{ group }} </h1>
    <p>  
      {{ group.description }}
    </p>
    {% for post in page_obj %} 
    {% include 'includes/article.html' with group_list=True %}
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
  Послeдние обновления на сайте
{% endblock %}
{% block content %}
  <div class="container py-5">     
    <h1>Последние обновления на сайте</h1>
      {% for post in page_obj %}
      {% include 'includes/article.html' with main_cite=True %}
          {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
  </div>
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
Пост {{ title }}
{% endblock %}
{% load thumbnail %}
{% block content %}
<div class="row">
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
      {% if post.group %}  
      <li class="list-group-item">
        Группа: {{ post.group.title }}
        <a href="{% url 'posts:group_list' post.group.slug %}">
          Все записи группы
        </a>
        {% endif %}
      </li>
      <li class="list-group-item">
        Автор: {{ post.author.get_full_name }}
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Всего постов автора:  <span >{{ post_count }}</span>
      </li>
      <li class="list-group-item">
        <a href="{% url 'posts:profile' post.author %}">
          Все посты пользователя
        </a>
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
       {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
           <img class="card-img my-2" src="{{ im.url }}">
       {% endthumbnail %}
    <p>
    {{ post.text }}
    </p>
    <!-- кнопка видна не авторизованному чуваку -->
    <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
      Редактировать запись
    </a>    
  </article>
</div> 
{% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html'%}
{% block title %}
 Профайл пользователя {{ author.get_full_name }}
{% endblock %}
{% block content %}
  <div class="container py-5">        
  <h1>Все посты пользователя {{ author.get_full_name }} </h1>
   <h3>Всего постов: {{ posts_count }}</h3>
      {% for post in page_obj %}
            {% include 'includes/article.html' %}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
  </div>
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div>
    </div> 
  </div>
</div>
{% endblock %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% include 'includes/form_errors.html' %}
          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}>
          {% csrf_token %}
              {% for field in form %}
                {% include 'includes/form_template.html' %}
              {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <a href="{% url 'users:login' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div>
      </div> 
    </div>
</div>
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
            {% include 'includes/form_errors.html' %}
            <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}
                {% for field in form %}
                    {% include 'includes/form_template.html' %}
                {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div>
        </div> 
      </div>
  </div>
{% endblock %}